inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/*_schema.rb'
    - 'db/schema.rb'
    - 'ac-wotlk/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Lint/Debugger:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes