default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: <%= ENV.fetch("DB_HOST") { "db" } %>

development:
  primary:
    <<: *default
    database: roa_development
  auth:
    <<: *default
    database: acore_auth
  world:
    <<: *default
    database: acore_world
  characters:
    <<: *default
    database: acore_characters

test:
  primary:
    <<: *default
    database: roa_test
  auth:
    <<: *default
    database: acore_test_auth
  world:
    <<: *default
    database: acore_test_world
  characters:
    <<: *default
    database: acore_test_characters